import { PrismaClient } from '@prisma/client';
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';

const adapter = new PrismaBetterSqlite3({
  url: 'file:dev.db',
});
const prisma = new PrismaClient({
  adapter,
  log: ['info', 'warn', 'error'],
});

async function main() {
  console.log('Seeding database...');
  // Clean database
  await prisma.project.deleteMany();
  await prisma.template.deleteMany();
  await prisma.asset.deleteMany();

  // Define assets
  const assetsToCreate = [
    {
      id: 'asset_shield_plus',
      name: 'Shield Plus Image',
      type: 'image',
      filePath: 'images/shield-plus.jpg',
      mime: 'image/jpeg',
      mimeType: 'image/jpeg',
      size: 102400,
      sizeBytes: 102400,
      width: 1200,
      height: 900,
      focalPointX: 0.5,
      focalPointY: 0.5,
    },
    {
      id: 'asset_p322',
      name: 'Sig P322 Image',
      type: 'image',
      filePath: 'images/p322.jpg',
      mime: 'image/jpeg',
      mimeType: 'image/jpeg',
      size: 98000,
      sizeBytes: 98000,
      width: 1200,
      height: 900,
      focalPointX: 0.5,
      focalPointY: 0.5,
    },
    {
      id: 'asset_atlas_apollo',
      name: 'Atlas Apollo Image',
      type: 'image',
      filePath: 'images/atlas-apollo.jpg',
      mime: 'image/jpeg',
      mimeType: 'image/jpeg',
      size: 250000,
      sizeBytes: 250000,
      width: 1200,
      height: 900,
      focalPointX: 0.5,
      focalPointY: 0.5,
    },
  ];

  for (const asset of assetsToCreate) {
    await prisma.asset.create({ data: asset });
  }

  // Define project sections and items
  const sections = [
    {
      id: 'sec_premium_used',
      title: 'Premium / Used',
      subtitle: 'High-end competition and pre-owned handguns',
      priority: 'high',
      layoutHint: 'grid',
      order: 0,
      items: [
        {
          id: 'item_atlas_apollo',
          sectionId: 'sec_premium_used',
          title: 'Atlas Gunworks Apollo V2 Perfect Zero',
          subtitle: '9mm | Used premium',
          description: 'Top-tier competition pistol with custom optic mount and ultra-light trigger.',
          price: 6250,
          priceDisplay: '$6,250',
          salePrice: null,
          badge: 'USED',
          imageAssetId: 'asset_atlas_apollo',
          priority: 'hero',
          visibility: 'visible',
          layoutHints: { cardSize: 'wide', imageFit: 'cover', preferredAspectRatio: '16:9' },
          metadata: { tags: ['premium', 'used', '9mm'] },
        },
        {
          id: 'item_staccato_xc',
          sectionId: 'sec_premium_used',
          title: 'Staccato XC 9mm',
          subtitle: '9mm | Compensated',
          description: 'Compensated duty and competition model with match-grade accuracy.',
          price: 4500,
          priceDisplay: '$4,500',
          salePrice: null,
          badge: 'USED',
          imageAssetId: null,
          priority: 'featured',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['premium', 'used', '9mm'] },
        },
        {
          id: 'item_nighthawk_grp',
          sectionId: 'sec_premium_used',
          title: 'Nighthawk Custom GRP',
          subtitle: '.45 ACP | Custom 1911',
          description: 'Hand-crafted classic 1911 with premium G10 grips and black nitride finish.',
          price: 3800,
          priceDisplay: '$3,800',
          salePrice: null,
          badge: 'USED',
          imageAssetId: null,
          priority: 'normal',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['premium', 'used', '45acp'] },
        },
      ],
    },
    {
      id: 'sec_compact_carry',
      title: 'Compact / Carry-Size',
      subtitle: 'Concealed carry and everyday defense options',
      priority: 'normal',
      layoutHint: 'grid',
      order: 1,
      items: [
        {
          id: 'item_shield_plus',
          sectionId: 'sec_compact_carry',
          title: 'Smith & Wesson M&P9 Shield Plus',
          subtitle: '9mm | Compact',
          description: 'Slim polymer frame with high capacity micro-compact magazine.',
          price: 530,
          priceDisplay: '$530',
          salePrice: null,
          badge: null,
          imageAssetId: 'asset_shield_plus',
          priority: 'normal',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['compact', '9mm'] },
        },
        {
          id: 'item_glock_43x',
          sectionId: 'sec_compact_carry',
          title: 'Glock 43X MOS',
          subtitle: '9mm | Slimline',
          description: 'Modular Optic System slimline grip frame with black slide.',
          price: 580,
          priceDisplay: '$580',
          salePrice: 520,
          badge: 'SALE',
          imageAssetId: null,
          priority: 'featured',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['compact', '9mm'] },
        },
        {
          id: 'item_p365_xl',
          sectionId: 'sec_compact_carry',
          title: 'Sig Sauer P365 XL',
          subtitle: '9mm | Subcompact',
          description: 'Extended slide and grip length micro-compact.',
          price: 680,
          priceDisplay: '$680',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'normal',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['compact', '9mm'] },
        },
        {
          id: 'item_hellcat_pro',
          sectionId: 'sec_compact_carry',
          title: 'Springfield Hellcat Pro',
          subtitle: '9mm | Compact OSP',
          description: 'Optic-ready compact format with melonite finish.',
          price: 640,
          priceDisplay: '$640',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'normal',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['compact', '9mm'] },
        },
        {
          id: 'item_cz_p10s',
          sectionId: 'sec_compact_carry',
          title: 'CZ P-10 S',
          subtitle: '9mm | Subcompact',
          description: 'Ergonomic striker-fired subcompact with crisp trigger break.',
          price: 450,
          priceDisplay: '$450',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'compact',
          visibility: 'visible',
          layoutHints: { cardSize: 'compact', imageFit: 'contain', preferredAspectRatio: '1:1' },
          metadata: { tags: ['compact', '9mm'] },
        },
      ],
    },
    {
      id: 'sec_range_training',
      title: 'Range / Training / .22 LR',
      subtitle: 'Low recoil target pistols and training handguns',
      priority: 'normal',
      layoutHint: 'grid',
      order: 2,
      items: [
        {
          id: 'item_p322',
          sectionId: 'sec_range_training',
          title: 'Sig Sauer P322',
          subtitle: '.22 LR | Range / training',
          description: 'High capacity rimfire training pistol with optic-ready slide.',
          price: 400,
          priceDisplay: '$400',
          salePrice: null,
          badge: null,
          imageAssetId: 'asset_p322',
          priority: 'normal',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['training', '22lr'] },
        },
        {
          id: 'item_glock_44',
          sectionId: 'sec_range_training',
          title: 'Glock 44',
          subtitle: '.22 LR | Plinker',
          description: 'Full-size hybrid steel-polymer slide training model.',
          price: 380,
          priceDisplay: '$380',
          salePrice: 340,
          badge: 'SALE',
          imageAssetId: null,
          priority: 'normal',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['training', '22lr'] },
        },
        {
          id: 'item_ruger_mark_iv',
          sectionId: 'sec_range_training',
          title: 'Ruger Mark IV Tactical',
          subtitle: '.22 LR | Target',
          description: 'Threaded barrel, gold-standard rimfire handgun with simple one-button takedown.',
          price: 610,
          priceDisplay: '$610',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'featured',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['training', '22lr'] },
        },
        {
          id: 'item_walther_wmp',
          sectionId: 'sec_range_training',
          title: 'Walther WMP',
          subtitle: '.22 WMR | Magnum',
          description: 'High performance magnum rimfire for varmint hunting and range target shooting.',
          price: 549,
          priceDisplay: '$549',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'compact',
          visibility: 'visible',
          layoutHints: { cardSize: 'compact', imageFit: 'contain', preferredAspectRatio: '1:1' },
          metadata: { tags: ['training', '22wmr'] },
        },
      ],
    },
    {
      id: 'sec_full_duty',
      title: 'Full-Size / Duty',
      subtitle: 'Standard issue and full frame home defense pistols',
      priority: 'normal',
      layoutHint: 'grid',
      order: 3,
      items: [
        {
          id: 'item_glock_17',
          sectionId: 'sec_full_duty',
          title: 'Glock 17 Gen 5',
          subtitle: '9mm | Duty standard',
          description: 'The standard choice for security forces worldwide with marksman barrel.',
          price: 590,
          priceDisplay: '$590',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'normal',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['fullsize', '9mm'] },
        },
        {
          id: 'item_p320_spectre',
          sectionId: 'sec_full_duty',
          title: 'Sig Sauer P320 Spectre Comp',
          subtitle: '9mm | Custom Works',
          description: 'Laser-engraved grip module with custom slide and integrated compensator.',
          price: 1400,
          priceDisplay: '$1,400',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'featured',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['fullsize', '9mm'] },
        },
        {
          id: 'item_cz_shadow2',
          sectionId: 'sec_full_duty',
          title: 'CZ Shadow 2 Orange',
          subtitle: '9mm | Competition ready',
          description: 'Hand-fitted match grade barrel with custom aluminum grip panels.',
          price: 2249,
          priceDisplay: '$2,249',
          salePrice: null,
          badge: 'NEW',
          imageAssetId: null,
          priority: 'normal',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['fullsize', '9mm'] },
        },
        {
          id: 'item_hk_vp9',
          sectionId: 'sec_full_duty',
          title: 'HK VP9',
          subtitle: '9mm | Striker standard',
          description: 'Ergonomic adjustable grip panels with premium HK trigger pull.',
          price: 749,
          priceDisplay: '$749',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'normal',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['fullsize', '9mm'] },
        },
        {
          id: 'item_mp9_m20',
          sectionId: 'sec_full_duty',
          title: 'Smith & Wesson M&P9 M2.0',
          subtitle: '9mm | Full size',
          description: 'Aggressive grip texture with stainless steel chassis system.',
          price: 620,
          priceDisplay: '$620',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'compact',
          visibility: 'visible',
          layoutHints: { cardSize: 'compact', imageFit: 'contain', preferredAspectRatio: '1:1' },
          metadata: { tags: ['fullsize', '9mm'] },
        },
      ],
    },
    {
      id: 'sec_revolvers',
      title: 'Revolvers',
      subtitle: 'Classic cylinder actions and heavy caliber defensive handguns',
      priority: 'low',
      layoutHint: 'grid',
      order: 4,
      items: [
        {
          id: 'item_colt_python',
          sectionId: 'sec_revolvers',
          title: 'Colt Python 3" .357 Mag',
          subtitle: '.357 Magnum | Classic',
          description: 'Semi-bright stainless steel finish with premium walnut target stock.',
          price: 1499,
          priceDisplay: '$1,499',
          salePrice: null,
          badge: 'NEW',
          imageAssetId: null,
          priority: 'featured',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['revolver', '357mag'] },
        },
        {
          id: 'item_sw_686',
          sectionId: 'sec_revolvers',
          title: 'Smith & Wesson Model 686',
          subtitle: '.357 Magnum | Duty',
          description: 'L-Frame revolver with satin finish and synthetic grip panels.',
          price: 949,
          priceDisplay: '$949',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'normal',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['revolver', '357mag'] },
        },
        {
          id: 'item_ruger_sp101',
          sectionId: 'sec_revolvers',
          title: 'Ruger SP101',
          subtitle: '.357 Magnum | Carry',
          description: 'Double action revolver with triple locking cylinder assembly.',
          price: 719,
          priceDisplay: '$719',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'normal',
          visibility: 'visible',
          layoutHints: { cardSize: 'normal', imageFit: 'contain', preferredAspectRatio: '4:3' },
          metadata: { tags: ['revolver', '357mag'] },
        },
        {
          id: 'item_taurus_856',
          sectionId: 'sec_revolvers',
          title: 'Taurus Defender 856',
          subtitle: '.38 Special | Light carry',
          description: 'Matte black polymer/steel revolver with night sight front blade.',
          price: 429,
          priceDisplay: '$429',
          salePrice: null,
          badge: null,
          imageAssetId: null,
          priority: 'compact',
          visibility: 'visible',
          layoutHints: { cardSize: 'compact', imageFit: 'contain', preferredAspectRatio: '1:1' },
          metadata: { tags: ['revolver', '38special'] },
        },
      ],
    },
  ];

  const projectContent = {
    schemaVersion: '1.0.0',
    id: 'project_cfc_tactical_board',
    name: 'CFC Tactical Handgun Board',
    type: 'inventory_board',
    canvas: {
      id: 'poster_11x17',
      name: 'Poster 11x17',
      widthPx: 3300,
      heightPx: 5100,
      dpi: 300,
      safeMarginPx: 120,
      unit: 'in',
    },
    brand: {
      id: 'brand_cfc_tactical',
      brandName: 'CFC Tactical',
      logoAssetId: null,
      website: 'https://cfctactical.com',
      phone: '781-858-4786',
      email: 'terry@cfctactical.com',
      defaultFooter: 'Questions? Reach out for guidance, testing, or additional insight.',
      defaultDisclaimer: 'Visit website for current availability. All purchases are subject to applicable federal, state, and local requirements.',
      colors: {
        background: '#181818',
        primary: '#ff6a00',
        secondary: '#ffffff',
        muted: '#a0a0a0',
      },
      styleKeywords: [
        'dark tactical',
        'premium',
        'industrial',
        'high contrast',
        'orange accents',
      ],
      fontPreferences: {
        heading: 'Inter',
        body: 'Inter',
        price: 'Inter',
      },
    },
    content: {
      headline: 'Handgun Inventory Board',
      subheadline: 'Current handgun options grouped by format and intended fit.',
      sections: sections,
    },
    layout: {
      elements: [],
      layoutFamily: 'inventory_board',
      density: 'normal',
      score: 100,
      warnings: [],
    },
    exportSettings: {
      exactTextOverlay: true,
      aiPolishMode: 'background_and_style',
      finalFormats: ['png', 'pdf'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  // Create Project
  await prisma.project.create({
    data: {
      id: 'project_cfc_tactical_board',
      name: 'CFC Tactical Handgun Board',
      type: 'inventory_board',
      contentJson: JSON.stringify(projectContent),
    },
  });

  // Seed a layout template
  const templateContent = {
    schemaVersion: '1.0.0',
    id: 'template_dark_tactical_v1',
    name: 'Dark Tactical Inventory Board',
    description: 'A dark matte premium layout with industrial texture, high contrast orange highlights.',
    category: 'inventory_board',
    layoutFamily: 'inventory_board',
    canvasPreset: {
      id: 'poster_11x17',
      name: 'Poster 11x17',
      widthPx: 3300,
      heightPx: 5100,
      dpi: 300,
      safeMarginPx: 120,
      unit: 'in',
    },
    isSystem: true,
    brandProfileOverride: {
      colors: {
        background: '#181818',
        primary: '#ff6a00',
        secondary: '#ffffff',
        muted: '#a0a0a0',
      },
      styleKeywords: ['dark tactical', 'premium', 'industrial', 'orange accents'],
    },
    defaultLayoutSettings: {
      density: 'normal',
      exactTextOverlay: true,
      aiPolishMode: 'background_and_style',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  await prisma.template.create({
    data: {
      id: 'template_dark_tactical_v1',
      name: 'Dark Tactical Inventory Board',
      layoutFamily: 'inventory_board',
      contentJson: JSON.stringify(templateContent),
    },
  });

  console.log('Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
